### ISSUE TITLE
ADC Reading Function

### ISSUE THREAD

**Issue by Adam-J-B** [Adam-J-B/Biosensor#17]
Write a function that updates the ADC readings. The function will be called using the following line:
``` readADC(); ```

The ```readADC``` function should update the ADC readings using the following calculations:
```
vol = (ads.readADC_Differential_0_1())*multiplier;  // Voltage reading
current = ((vol)/(98.2));  // ohm's law
anodePotential = ((ads.readADC_Differential_2_3())*multiplier)/1000;
cell_vol = ((ads.readADC_SingleEnded(1))*multiplier)/1000;
```

**Comment by Elzabad** [comment]
Completed and merged to master
